# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nGM-UBaRjtSx64sd_Z3ovsEpXsog-vKu
"""

import numpy as np
import matplotlib.pyplot as plt

# X qiymatlarini yaratamiz
x = np.linspace(0, 2 * np.pi, 100)  # 0 dan 2π gacha bo'lgan 100 ta nuqta
y = np.sin(x)  # sinus funksiyasi

# Grafikni chizamiz
plt.plot(x, y, label='sin(x)', color='blue')
plt.title("Sinus funksiyasining grafigi")
plt.xlabel("x (radianlarda)")
plt.ylabel("sin(x)")
plt.axhline(0, color='black', linewidth=0.5, linestyle='--')  # x o'qi
plt.axvline(0, color='black', linewidth=0.5, linestyle='--')  # y o'qi
plt.grid(True, linestyle='--', alpha=0.7)
plt.legend()
plt.show()


import numpy as np
import matplotlib.pyplot as plt

# Tasodifiy nuqtalarni yaratamiz
np.random.seed(42)  # Takrorlanuvchanlik uchun
x = np.random.uniform(0, 10, 50)  # X qiymatlari (0 dan 10 gacha)
y = np.random.uniform(0, 10, 50)  # Y qiymatlari (0 dan 10 gacha)

# Scatter grafikka chizamiz
plt.scatter(x, y, color='blue', label='Nuqtalar', alpha=0.8, edgecolor='black')
plt.title("Tasodifiy Nuqtalar Scatter Grafiki")
plt.xlabel("X qiymatlari")
plt.ylabel("Y qiymatlari")
plt.grid(True, linestyle='--', alpha=0.7)
plt.legend()
plt.show()